### PR TITLE
major changes to layout and components

### PR DESCRIPTION
**Pull request by william-man**
Below are the changes to the layout and components:

App.jsx:
-added error state variable along with its toggle functions that is passed into the <SideBar /> component which is then passed into the validateIngredientsQuery function to allow it to change the state of the error component.

-added a parent element to the sidebar to make the layout more rigid and structured.

App.css:
-added display: grid property to the root element to better control the transformation of the layout following the figma plan.

-currently transformations for screen widths under 1400 causes the sidebar to break

Welcome, Modal, Error components:
-all 3 components should now have the same width as the parent component, any position properties and margins have been removed so all 3 components now sit cleanly ontop of the area of the main element.

Index.css-:

-added major colour schemes as variables inside :root
-added max width for the sidebar
-added border-radius to keep all element shapes uniform

Error.jsx:
-fixed typo error, replaced the ' with &apos;.

Sidebar.jsx:
-integrated error state functions to be used for the error function

Welcome.jsx:
-removed the parent element of the heading and combined its css into the overlay. 

validateIngredientQuery.js:

-added showError and hideError state functions into the error function. Now there is no need to comment out the css to display it; an invalid search request using your personal key imported from a .env file should enable testing its behaviour.

Current Major bugs:
-The behaviour of the sidebar breaks under screen widths of 1400 and transforms incorrectly.
-There appears to be 2 parent nav elements and might be causing transformation issues.

Minor bug:
-in the validateIngredientQuery.js error function; the error component does not display the search terms to the user when there is a bad input. It does not update the inner HTML before it is displayed.

### CODE REVIEW

**Review by Oviep — CHANGES_REQUESTED** [review]
These changes need to be discussed with the team

**Comment by william-man** [comment]
Update: removed changes error state variables, its state functions and props thats passed into the sidebar and then into the validation function.

Moved Sidebar component into the aside parent element to remove desktop display errors.

**Comment by william-man** [comment]
Fixed layout bugs, now the sidebar transforms at screen width 1500px. The sidebar now stacks ontop of the display area

**Comment by william-man** [comment]
Added comments to respective code.

**Pull request closed without merging**
